services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4013:4013"
    env_file:
      - .env
      
  frontend:
    build:
      context: ./docs/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
